global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'team']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'mattermost'

receivers:
  - name: 'mattermost'
    webhook_configs:
      - url: '${MATTERMOST_WEBHOOK_URL}'
        send_resolved: true
        http_config:
          tls_config:
            insecure_skip_verify: true
        message: '{{ template "mattermost.message" . }}'

  - name: 'email'
    email_configs:
      - to: 'admin@company.com'
        from: 'alertmanager@company.com'
        smarthost: 'smtp.company.com:587'
        auth_username: 'alertmanager@company.com'
        auth_password: 'password'
        send_resolved: true

templates:
  - '/etc/alertmanager/template/*.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'team'] 